name: Continuous Integration

on: [push]

jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.0']
        name: PHP ${{ matrix.php-versions }}
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none
                    tools: composer:v1

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --no-interaction --optimize-autoloader
                
            -   name: Run PHPCS
                run: vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

            -   name: Run PHPUnit
                run: vendor/bin/phpunit
